config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only: [:create,:destroy]

  devise_for :users
  root'welcome#index'
  get 'my_portfolio', to:'users#my_portfolio'
  get 'search_stock', to: 'stocks#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks, dependent: :destroy
  has_many :users, through: :user_stocks
  validates :name, :ticker, presence: true
  def self.new_lookup(ticker_symbol)
    client = IEX::Api::Client.new(
      publishable_token: 'pk_17764d149d20450aba91b2b86ab75288',

      endpoint: 'https://cloud.iexapis.com/v1')

    begin

    new(ticker: ticker_symbol, name: client.company(ticker_symbol).company_name, lastprice: client.price(ticker_symbol))
  rescue => exception
    return nil
  end
  end
  def self.check_db(ticker_symbol)
    where(ticker: ticker_symbol).first
  end
  end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks, dependent: :destroy
  has_many :stocks, through: :user_stocks
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable




         def stock_already_tracked?(symbol)
          stock = Stock.check_db symbol
          return false unless stock

          stocks.where(id: stock.id).exists?
        end


        def can_track_stock? symbol
           !stock_already_tracked?(symbol)
        end

end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end


end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def search
    if params[:stock].present?
@stock= Stock.new_lookup(params[:stock])
if @stock

render  "stocks/results"
else
  flash[:alert]="please enter a valid symbol"
  redirect_to my_portfolio_path


end
    else
      flash[:alert]="Please enter a symnbol to search"
      redirect_to my_portfolio_path

  end

end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController

  def create
    stock = Stock.check_db(params[:ticker])
    if stock.blank?
      stock = Stock.new_lookup(params[:ticker])
      stock.save
    end
      @user_stock = UserStock.create(user: current_user, stock: stock)
      flash[:notice] = "Stock #{stock.name} was successfully added to your portfolio"
      redirect_to my_portfolio_path

    end
    def destroy
      stock = Stock.find params[:id]

      UserStock.where(user_id: current_user.id, stock_id: stock.id).first.destroy
      flash[:notice] = "#{stock.name} (#{stock.ticker}) was removed from your portfolio"
      redirect_to my_portfolio_path
    end



  end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def my_portfolio
    @tracked_stocks = current_user.stocks


  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_messages.html.erb
  <p class="notice"><%= notice %></p>

       <p class="alert"><%= alert %></p>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container">

    <%= link_to "FinanceTracker" , root_path, class:"navbar-brand" %>
    <%  if current_user %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
              <%= link_to "My Portfolio",my_portfolio_path, class: "nav-link" %>
          </li>
       

        </ul>
        <ul class='nav-item'>
          <li class='nav-item'>
            <%= link_to("Logout", destroy_user_session_path, class: "btn btn-outline-danger", data: { "turbo-method": :delete }
           ) %>
          </li>
        </ul>
      
      </div>
      <% end %>
    
</nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceTrackerApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

      <%=   render "layouts/navigation"   %>
   
<div  class="container">
<%= render "layouts/messages" %>
    <%= yield %>
    </div>
  
  </body>
</html>

app/views/stocks/_list.html.erb
        
        
        <% if !@tracked_stocks.empty? %>
    
    
    <div class ="row">
      <div class ="col-9">

<table class="table  table-bordered table-hover">
  <thead>
    <tr>
      <th scope="col">Ticker</th>
      <th scope="col">Name</th>
      <th scope="col">Price</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
       <% @tracked_stocks.each do |stock| %>
    <tr>
      <th scope="row">  <%= stock.ticker %>  </th>
      <td>  <%= stock.name %> </td>
      <td> <%= stock.lastprice %></td>
      <td>   <%= link_to 'Remove', user_stock_path(stock),    method: :delete, data: { "turbo-method": :delete }, class: 'btn btn-sm btn-warning',data: { turbo_method: :delete, turbo_confirm: "Are you sure?"}   %> </td>
    </tr>
<% end %>
  </tbody>
</table>
</div>
</div>
<% end %>

app/views/stocks/results.html.erb
<div class="search-area">
<h3>Search Stocks</h3>
<%= form_tag search_stock_path, method: :get do %>
    <div class="form-group row">
      <div class="col-sm-9 no-right-padding">
        <%= text_field_tag :stock, params[:stock], placeholder: "tock ticker symbol", autofocus: true, class: "form-control form-control-lg" %>
      </div>
       <div class="col-sm-3 no-left-padding">
                 <%= button_tag type: :submit, class: "btn btn-success" do %>
                   <%= fa_icon 'search 2x' %>
        <% end %>
      </div>
    </div>
  <% end %>



<% if @stock %>  
  <div class="card card-header results-block">
    <strong>Symbol: </strong> <%= @stock.ticker %>
    <strong>Name: </strong> <%= @stock.name %>
    <strong>Price: </strong> <%= @stock.lastprice %>
    <% if current_user.can_track_stock? (@stock.ticker) %>
    
      <%= link_to 'Add to portfolio', user_stocks_path(user: current_user, ticker: @stock.ticker),
                                    class: "btn btn-sm btn-success", data: { turbo_method: :post } %>
                                    <% else%>
                                      <span class="label label-default">
                                           You are already tracking

                                          

                                           <%  if current_user.stock_already_tracked?(@stock.ticker) %>
                                           this stock
                                            <% end %>
                                         </ span >

                                           <% end %>

    </div>
      <% end %>
      

app/views/users/my_portfolio.html.erb
<h1>My_Portfolio</h1> 

<div class="search-area">
<h3>Search Stocks</h3>
<%= form_tag search_stock_path, method: :get do %>
    <div class="form-group row">
      <div class="col-sm-9 no-right-padding">
        <%= text_field_tag :stock, params[:stock], placeholder: "tock ticker symbol", autofocus: true, class: "form-control form-control-lg" %>
      </div>
       <div class="col-sm-3 no-left-padding">
                 <%= button_tag type: :submit, class: "btn btn-success" do %>
                   <%= fa_icon 'search 2x' %>
        <% end %>
      </div>
    </div>
  <% end %>

</div>
 
  
  <%= render 'stocks/list' %>
  

app/views/welcome/index.html.erb
<h1>Welcome to Finance Tracker</h1>